package bfst21.models;


public enum DisplayOption {
    DISPLAY_KD_TREE,
    DISPLAY_GRAPH,
    DISPLAY_DIJKSTRA,
    DISPLAY_RELATIONS,
    DISPLAY_ISLAND,
    DISPLAY_WATERWAY,
    DISPLAY_WATER,
    DISPLAY_LANDUSE,
    DISPLAY_FOREST,
    DISPLAY_CYCLEWAY,
    DISPLAY_FOOTWAY,
    DISPLAY_PEDESTRIAN,
    DISPLAY_ROAD,
    DISPLAY_RESIDENTIAL,
    DISPLAY_TRUNK,
    DISPLAY_MOTORWAY,
    DISPLAY_TERTIARY,
    DISPLAY_PRIMARY,
    DISPLAY_BUILDING,
    DISPLAY_UNKNOWN,
    DISPLAY_RAILWAY,
    DISPLAY_AEROWAY,
    DISPLAY_FERRY,
    DISPLAY_TEXT
}
