package bfst21.models;

public enum Option {
    LOAD_RELATIONS,

    USE_KD_TREE,
    USE_R_TREE,

    SAVE_OBJ_FILE,

    DISPLAY_KD_TREE,
    DISPLAY_GRAPH,

    DISPLAY_ISLAND,
    DISPLAY_WATER,
    DISPLAY_WATERWAY,
    DISPLAY_LANDUSE,
    DISPLAY_CYCLEWAY,
    DISPLAY_FOOTWAY,
    DISPLAY_ROAD,
    DISPLAY_RESIDENTIAL,
    DISPLAY_TRUNK,
    DISPLAY_MOTORWAY,
    DISPLAY_TERTIARY,
    DISPLAY_PRIMARY,
    DISPLAY_BUILDING,
    DISPLAY_UNKNOWN
}
